//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.LARS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARS_ApprenticeshipFunding
    {
        public string ApprenticeshipType { get; set; }
        public int ApprenticeshipCode { get; set; }
        public int ProgType { get; set; }
        public int PwayCode { get; set; }
        public string FundingCategory { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public Nullable<int> BandNumber { get; set; }
        public Nullable<decimal> CoreGovContributionCap { get; set; }
        public Nullable<decimal> C1618Incentive { get; set; }
        public Nullable<decimal> C1618ProviderAdditionalPayment { get; set; }
        public Nullable<decimal> C1618EmployerAdditionalPayment { get; set; }
        public Nullable<decimal> C1618FrameworkUplift { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<decimal> ReservedValue2 { get; set; }
        public Nullable<decimal> ReservedValue3 { get; set; }
        public Nullable<decimal> MaxEmployerLevyCap { get; set; }
        public string FundableWithoutEmployer { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
        public Nullable<decimal> CareLeaverAdditionalPayment { get; set; }
    }
}
