//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.LARS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARS_StandardMetaData
    {
        public int StandardCode { get; set; }
        public string RoleOverview { get; set; }
        public string JobRoles { get; set; }
        public string Keywords { get; set; }
        public string EntryRequirements { get; set; }
        public string Learning { get; set; }
        public string Qualifications { get; set; }
        public string ProfessionalRegistration { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual LARS_Standard LARS_Standard { get; set; }
    }
}
