//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.LARS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARS_SupersedingFrameworks
    {
        public int OldFworkCode { get; set; }
        public int OldProgType { get; set; }
        public int OldPwayCode { get; set; }
        public int NewFworkCode { get; set; }
        public int NewProgType { get; set; }
        public int NewPwayCode { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual LARS_Framework LARS_Framework { get; set; }
        public virtual LARS_Framework LARS_Framework1 { get; set; }
    }
}
