//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.LARS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARS_AnnualValue
    {
        public string LearnAimRef { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public Nullable<int> BasicSkills { get; set; }
        public Nullable<int> BasicSkillsBroadType { get; set; }
        public Nullable<int> BasicSkillsType { get; set; }
        public Nullable<int> BasicSkillsParticipation { get; set; }
        public Nullable<int> FullLevel2EntitlementCategory { get; set; }
        public Nullable<decimal> FullLevel2Percent { get; set; }
        public Nullable<int> FullLevel3EntitlementCategory { get; set; }
        public Nullable<decimal> FullLevel3Percent { get; set; }
        public Nullable<int> MI_FullLevel2 { get; set; }
        public Nullable<decimal> MI_FullLevel2Percent { get; set; }
        public Nullable<int> MI_FullLevel3 { get; set; }
        public Nullable<decimal> MI_FullLevel3Percent { get; set; }
        public Nullable<int> OfQualValid19Plus { get; set; }
        public Nullable<int> SfaApprovalStatus { get; set; }
        public Nullable<int> UKCESSector { get; set; }
        public string UKCESSubSector { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual LARS_LearningDelivery LARS_LearningDelivery { get; set; }
    }
}
