//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.LARS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LARS_StandardValidity
    {
        public int StandardCode { get; set; }
        public string ValidityCategory { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> LastNewStartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual LARS_Standard LARS_Standard { get; set; }
    }
}
