//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.LARS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBStandardLookup
    {
        public int StandardNumber { get; set; }
        public string StandardDesc { get; set; }
        public string Sector { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> CoreGovContCap { get; set; }
        public Nullable<decimal> YoungAppIncentive { get; set; }
        public Nullable<decimal> SmallBusIncentive { get; set; }
        public Nullable<decimal> AchIncentive { get; set; }
        public System.DateTime ValuesEffectiveFrom { get; set; }
        public Nullable<System.DateTime> ValuesEffectiveTo { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Modified_By { get; set; }
    }
}
