CREATE PROCEDURE [Staging].[usp_Process_LearningDelivery]
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRY
		
		MERGE INTO [Core].[LARS_LearningDelivery] AS Target
		USING (
				SELECT   [LearnAimRef]
						,[EffectiveFrom]
						,[EffectiveTo]
						,[LearnAimRefTitle]
						,[LearnAimRefType]
						,[NotionalNVQLevel]
						,[NotionalNVQLevelv2]
						,[AwardOrgAimRef]
						,[CertificationEndDate]
						,[OperationalStartDate]
						,[OperationalEndDate]
						,[EnglandFEHEStatus]
						,[CreditBasedFwkType]
						,[QltyAssAgencyType]
						,[OfQualGlhMin]
						,[OfQualGlhMax]
						,[DiplomaLinesOfLearning]
						,[FrameworkCommonComponent]
						,[LTRCPWithProviderUpliftFactor]
						,[EntrySubLevel]
						,[SuccessRateMapCode]
						,[AccreditiedNotDfESApproved]
						,[AccreditiedMayPossDfESApproved]
						,[JointInvestmentProgrammeOnly]
						,[OLASSOnly]
						,[UnemployedOnly]
						,[IndependentLivingSkills]
						,[AdditionalOrSpecialistLearning]
						,[EnglPrscID]
						,[Vocational]
						,[AwardOrgCode]
						,[UnitType]
						,[LearningDeliveryGenre]
						,[ApprovedEmployerSchemeFramework]
						,[FrameworkCompletionClassCode]
						,[OfQualOfferedEngland]
						,[OfqualPurpose]
						,[OfqualSubPurpose]
						,[RgltnStartDate]
						,[SourceQualType]
						,[SourceSystemRef]
						,[SourceURLRef]
						,[SourceURLLinkType]
						,[OccupationalIndicator]
						,[AccessHEIndicator]
						,[KeySkillsIndicator]
						,[FunctionalSkillsIndicator]
						,[GCEIndicator]
						,[GCSEIndicator]
						,[ASLevelIndicator]
						,[A2LevelIndicator]
						,[ALevelIndicator]
						,[QCFIndicator]
						,[QCFDiplomaIndicator]
						,[QCFCertificateIndicator]
						,[EFAEnglishGCSE]
						,[EFAMathsGCSE]
						,[EFACOFType]
						,[SFAFundedIndicator]
						,[DanceAndDramaIndicator]
						,[AvailabiltyStatus]
						,[Note]
						,[LearnDirectClassSystemCode1]
						,[LearnDirectClassSystemCode2]
						,[LearnDirectClassSystemCode3]
						,[RegulatedCreditValue]
						,[SectorSubjectAreaTier1]
						,[SectorSubjectAreaTier2]
						,[MI_NotionalNVQLevel]
						,[MI_NotionalNVQLevelv2]
					    ,[GuidedLearningHours]
					    ,[DirectStudyHours]
					    ,[DedicatedAssessmentHours]
					    ,[TotalQualificationTime]
						,[Created_On]
					    ,[Created_By]
					    ,[Modified_On]
					    ,[Modified_By]
				  FROM [Staging].[LARS_LearningDelivery]
			  )
			  AS Source 
		    ON RTRIM(Target.[LearnAimRef]) = Source.[LearnAimRef]
		  WHEN MATCHED 
				AND EXISTS 
					(	SELECT 
							 Target.[LearnAimRef]
							,Target.[EffectiveFrom]
							,Target.[EffectiveTo]
							,Target.[LearnAimRefTitle]
							,Target.[LearnAimRefType]
							,Target.[NotionalNVQLevel]
							,Target.[NotionalNVQLevelv2]
							,Target.[AwardOrgAimRef]
							,Target.[CertificationEndDate]
							,Target.[OperationalStartDate]
							,Target.[OperationalEndDate]
							,Target.[EnglandFEHEStatus]
							,Target.[CreditBasedFwkType]
							,Target.[QltyAssAgencyType]
							,Target.[OfQualGlhMin]
							,Target.[OfQualGlhMax]
							,Target.[DiplomaLinesOfLearning]
							,Target.[FrameworkCommonComponent]
							,Target.[LTRCPWithProviderUpliftFactor]
							,Target.[EntrySubLevel]
							,Target.[SuccessRateMapCode]
							,Target.[AccreditiedNotDfESApproved]
							,Target.[AccreditiedMayPossDfESApproved]
							,Target.[JointInvestmentProgrammeOnly]
							,Target.[OLASSOnly]
							,Target.[UnemployedOnly]
							,Target.[IndependentLivingSkills]
							,Target.[AdditionalOrSpecialistLearning]
							,Target.[EnglPrscID]
							,Target.[Vocational]
							,Target.[AwardOrgCode]
							,Target.[UnitType]
							,Target.[LearningDeliveryGenre]
							,Target.[ApprovedEmployerSchemeFramework]
							,Target.[FrameworkCompletionClassCode]
							,Target.[OfQualOfferedEngland]
							,Target.[OfqualPurpose]
							,Target.[OfqualSubPurpose]
							,Target.[RgltnStartDate]
							,Target.[SourceQualType]
							,Target.[SourceSystemRef]
							,Target.[SourceURLRef]
							,Target.[SourceURLLinkType]
							,Target.[OccupationalIndicator]
							,Target.[AccessHEIndicator]
							,Target.[KeySkillsIndicator]
							,Target.[FunctionalSkillsIndicator]
							,Target.[GCEIndicator]
							,Target.[GCSEIndicator]
							,Target.[ASLevelIndicator]
							,Target.[A2LevelIndicator]
							,Target.[ALevelIndicator]
							,Target.[QCFIndicator]
							,Target.[QCFDiplomaIndicator]
							,Target.[QCFCertificateIndicator]
							,Target.[EFAEnglishGCSE]
							,Target.[EFAMathsGCSE]
							,Target.[EFACOFType]
							,Target.[SFAFundedIndicator]
							,Target.[DanceAndDramaIndicator]
							,Target.[AvailabiltyStatus]
							,Target.[Note]
							,Target.[LearnDirectClassSystemCode1]
							,Target.[LearnDirectClassSystemCode2]
							,Target.[LearnDirectClassSystemCode3]
							,Target.[RegulatedCreditValue]
							,Target.[SectorSubjectAreaTier1]
							,Target.[SectorSubjectAreaTier2]
							,Target.[MI_NotionalNVQLevel]
							,Target.[MI_NotionalNVQLevelv2]
							,Target.[GuidedLearningHours]
							,Target.[DirectStudyHours]
							,Target.[DedicatedAssessmentHours]
							,Target.[TotalQualificationTime]						
					EXCEPT 
						SELECT 
							 Source.[LearnAimRef]
							,Source.[EffectiveFrom]
							,Source.[EffectiveTo]
							,Source.[LearnAimRefTitle]
							,Source.[LearnAimRefType]
							,Source.[NotionalNVQLevel]
							,Source.[NotionalNVQLevelv2]
							,Source.[AwardOrgAimRef]
							,Source.[CertificationEndDate]
							,Source.[OperationalStartDate]
							,Source.[OperationalEndDate]
							,Source.[EnglandFEHEStatus]
							,Source.[CreditBasedFwkType]
							,Source.[QltyAssAgencyType]
							,Source.[OfQualGlhMin]
							,Source.[OfQualGlhMax]
							,Source.[DiplomaLinesOfLearning]
							,Source.[FrameworkCommonComponent]
							,Source.[LTRCPWithProviderUpliftFactor]
							,Source.[EntrySubLevel]
							,Source.[SuccessRateMapCode]
							,Source.[AccreditiedNotDfESApproved]
							,Source.[AccreditiedMayPossDfESApproved]
							,Source.[JointInvestmentProgrammeOnly]
							,Source.[OLASSOnly]
							,Source.[UnemployedOnly]
							,Source.[IndependentLivingSkills]
							,Source.[AdditionalOrSpecialistLearning]
							,Source.[EnglPrscID]
							,Source.[Vocational]
							,Source.[AwardOrgCode]
							,Source.[UnitType]
							,Source.[LearningDeliveryGenre]
							,Source.[ApprovedEmployerSchemeFramework]
							,Source.[FrameworkCompletionClassCode]
							,Source.[OfQualOfferedEngland]
							,Source.[OfqualPurpose]
							,Source.[OfqualSubPurpose]
							,Source.[RgltnStartDate]
							,Source.[SourceQualType]
							,Source.[SourceSystemRef]
							,Source.[SourceURLRef]
							,Source.[SourceURLLinkType]
							,Source.[OccupationalIndicator]
							,Source.[AccessHEIndicator]
							,Source.[KeySkillsIndicator]
							,Source.[FunctionalSkillsIndicator]
							,Source.[GCEIndicator]
							,Source.[GCSEIndicator]
							,Source.[ASLevelIndicator]
							,Source.[A2LevelIndicator]
							,Source.[ALevelIndicator]
							,Source.[QCFIndicator]
							,Source.[QCFDiplomaIndicator]
							,Source.[QCFCertificateIndicator]
							,Source.[EFAEnglishGCSE]
							,Source.[EFAMathsGCSE]
							,Source.[EFACOFType]
							,Source.[SFAFundedIndicator]
							,Source.[DanceAndDramaIndicator]
							,Source.[AvailabiltyStatus]
							,Source.[Note]
							,Source.[LearnDirectClassSystemCode1]
							,Source.[LearnDirectClassSystemCode2]
							,Source.[LearnDirectClassSystemCode3]
							,Source.[RegulatedCreditValue]
							,Source.[SectorSubjectAreaTier1]
							,Source.[SectorSubjectAreaTier2]
							,Source.[MI_NotionalNVQLevel]
							,Source.[MI_NotionalNVQLevelv2]
							,Source.[GuidedLearningHours]
							,Source.[DirectStudyHours]
							,Source.[DedicatedAssessmentHours]
							,Source.[TotalQualificationTime]
							--,Source.[Created_On]
							--,Source.[Created_By]
							--,Source.[Modified_On]
							--,Source.[Modified_By]
					)
		  THEN
			UPDATE SET   [EffectiveFrom]  = Source.[EffectiveFrom]
						,[EffectiveTo]  = Source.[EffectiveTo]
						,[LearnAimRefTitle]  = Source.[LearnAimRefTitle]
						,[LearnAimRefType]  = Source.[LearnAimRefType]
						,[NotionalNVQLevel]  = Source.[NotionalNVQLevel]
						,[NotionalNVQLevelv2]  = Source.[NotionalNVQLevelv2]
						,[AwardOrgAimRef]  = Source.[AwardOrgAimRef]
						,[CertificationEndDate]  = Source.[CertificationEndDate]
						,[OperationalStartDate]  = Source.[OperationalStartDate]
						,[OperationalEndDate]  = Source.[OperationalEndDate]
						,[EnglandFEHEStatus]  = Source.[EnglandFEHEStatus]
						,[CreditBasedFwkType]  = Source.[CreditBasedFwkType]
						,[QltyAssAgencyType]  = Source.[QltyAssAgencyType]
						,[OfQualGlhMin]  = Source.[OfQualGlhMin]
						,[OfQualGlhMax]  = Source.[OfQualGlhMax]
						,[DiplomaLinesOfLearning]  = Source.[DiplomaLinesOfLearning]
						,[FrameworkCommonComponent]  = Source.[FrameworkCommonComponent]
						,[LTRCPWithProviderUpliftFactor]  = Source.[LTRCPWithProviderUpliftFactor]
						,[EntrySubLevel]  = Source.[EntrySubLevel]
						,[SuccessRateMapCode]  = Source.[SuccessRateMapCode]
						,[AccreditiedNotDfESApproved]  = Source.[AccreditiedNotDfESApproved]
						,[AccreditiedMayPossDfESApproved]  = Source.[AccreditiedMayPossDfESApproved]
						,[JointInvestmentProgrammeOnly]  = Source.[JointInvestmentProgrammeOnly]
						,[OLASSOnly]  = Source.[OLASSOnly]
						,[UnemployedOnly]  = Source.[UnemployedOnly]
						,[IndependentLivingSkills]  = Source.[IndependentLivingSkills]
						,[AdditionalOrSpecialistLearning]  = Source.[AdditionalOrSpecialistLearning]
						,[EnglPrscID]  = Source.[EnglPrscID]
						,[Vocational]  = Source.[Vocational]
						,[AwardOrgCode]  = Source.[AwardOrgCode]
						,[UnitType]	  = Source.[UnitType]
						,[LearningDeliveryGenre]  = Source.[LearningDeliveryGenre]
						,[ApprovedEmployerSchemeFramework]  = Source.[ApprovedEmployerSchemeFramework]
						,[FrameworkCompletionClassCode]  = Source.[FrameworkCompletionClassCode]
						,[OfQualOfferedEngland]  = Source.[OfQualOfferedEngland]
						,[OfqualPurpose]  = Source.[OfqualPurpose]
						,[OfqualSubPurpose]  = Source.[OfqualSubPurpose]
						,[RgltnStartDate]  = Source.[RgltnStartDate]
						,[SourceQualType]  = Source.[SourceQualType]
						,[SourceSystemRef]  = Source.[SourceSystemRef]
						,[SourceURLRef]  = Source.[SourceURLRef]
						,[SourceURLLinkType]  = Source.[SourceURLLinkType]
						,[OccupationalIndicator]  = Source.[OccupationalIndicator]
						,[AccessHEIndicator]  = Source.[AccessHEIndicator]
						,[KeySkillsIndicator]  = Source.[KeySkillsIndicator]
						,[FunctionalSkillsIndicator]  = Source.[FunctionalSkillsIndicator]
						,[GCEIndicator]  = Source.[GCEIndicator]
						,[GCSEIndicator]  = Source.[GCSEIndicator]
						,[ASLevelIndicator]  = Source.[ASLevelIndicator]
						,[A2LevelIndicator]  = Source.[A2LevelIndicator]
						,[ALevelIndicator]  = Source.[ALevelIndicator]
						,[QCFIndicator]  = Source.[QCFIndicator]
						,[QCFDiplomaIndicator]  = Source.[QCFDiplomaIndicator]
						,[QCFCertificateIndicator]  = Source.[QCFCertificateIndicator]
						,[EFAEnglishGCSE]  = Source.[EFAEnglishGCSE]
						,[EFAMathsGCSE]  = Source.[EFAMathsGCSE]
						,[EFACOFType]  = Source.[EFACOFType]
						,[SFAFundedIndicator]  = Source.[SFAFundedIndicator]
						,[DanceAndDramaIndicator]  = Source.[DanceAndDramaIndicator]
						,[AvailabiltyStatus]  = Source.[AvailabiltyStatus]
						,[Note]		  = Source.[Note]
						,[LearnDirectClassSystemCode1]  = Source.[LearnDirectClassSystemCode1]
						,[LearnDirectClassSystemCode2]  = Source.[LearnDirectClassSystemCode2]
						,[LearnDirectClassSystemCode3]  = Source.[LearnDirectClassSystemCode3]
						,[RegulatedCreditValue]  = Source.[RegulatedCreditValue]
						,[SectorSubjectAreaTier1]  = Source.[SectorSubjectAreaTier1]
						,[SectorSubjectAreaTier2]  = Source.[SectorSubjectAreaTier2]
						,[MI_NotionalNVQLevel]  = Source.[MI_NotionalNVQLevel]
						,[MI_NotionalNVQLevelv2]  = Source.[MI_NotionalNVQLevelv2]
						,[GuidedLearningHours]  = Source.[GuidedLearningHours]
						,[DirectStudyHours]  = Source.[DirectStudyHours]
						,[DedicatedAssessmentHours]  = Source.[DedicatedAssessmentHours]
						,[TotalQualificationTime]  = Source.[TotalQualificationTime]
						,[Created_On] = Source.[Created_On]
						,[Created_By] = Source.[Created_By]
						,[Modified_On] = Source.[Modified_On]
						,[Modified_By] = Source.[Modified_By]
		WHEN NOT MATCHED BY TARGET THEN
		INSERT	    (    [LearnAimRef]						
						,[EffectiveFrom]
						,[EffectiveTo]
						,[LearnAimRefTitle]
						,[LearnAimRefType]
						,[NotionalNVQLevel]
						,[NotionalNVQLevelv2]
						,[AwardOrgAimRef]
						,[CertificationEndDate]
						,[OperationalStartDate]
						,[OperationalEndDate]
						,[EnglandFEHEStatus]
						,[CreditBasedFwkType]
						,[QltyAssAgencyType]
						,[OfQualGlhMin]
						,[OfQualGlhMax]
						,[DiplomaLinesOfLearning]
						,[FrameworkCommonComponent]
						,[LTRCPWithProviderUpliftFactor]
						,[EntrySubLevel]
						,[SuccessRateMapCode]
						,[AccreditiedNotDfESApproved]
						,[AccreditiedMayPossDfESApproved]
						,[JointInvestmentProgrammeOnly]
						,[OLASSOnly]
						,[UnemployedOnly]
						,[IndependentLivingSkills]
						,[AdditionalOrSpecialistLearning]
						,[EnglPrscID]
						,[Vocational]
						,[AwardOrgCode]
						,[UnitType]
						,[LearningDeliveryGenre]
						,[ApprovedEmployerSchemeFramework]
						,[FrameworkCompletionClassCode]
						,[OfQualOfferedEngland]
						,[OfqualPurpose]
						,[OfqualSubPurpose]
						,[RgltnStartDate]
						,[SourceQualType]
						,[SourceSystemRef]
						,[SourceURLRef]
						,[SourceURLLinkType]
						,[OccupationalIndicator]
						,[AccessHEIndicator]
						,[KeySkillsIndicator]
						,[FunctionalSkillsIndicator]
						,[GCEIndicator]
						,[GCSEIndicator]
						,[ASLevelIndicator]
						,[A2LevelIndicator]
						,[ALevelIndicator]
						,[QCFIndicator]
						,[QCFDiplomaIndicator]
						,[QCFCertificateIndicator]
						,[EFAEnglishGCSE]
						,[EFAMathsGCSE]
						,[EFACOFType]
						,[SFAFundedIndicator]
						,[DanceAndDramaIndicator]
						,[AvailabiltyStatus]
						,[Note]
						,[LearnDirectClassSystemCode1]
						,[LearnDirectClassSystemCode2]
						,[LearnDirectClassSystemCode3]
						,[RegulatedCreditValue]
						,[SectorSubjectAreaTier1]
						,[SectorSubjectAreaTier2]
						,[MI_NotionalNVQLevel]
						,[MI_NotionalNVQLevelv2]
						,[GuidedLearningHours]
						,[DirectStudyHours]
						,[DedicatedAssessmentHours]
						,[TotalQualificationTime] 
						,[Created_On]
						,[Created_By]
						,[Modified_On]
						,[Modified_By]
					)
			VALUES (	 Source.[LearnAimRef]						
						,Source.[EffectiveFrom]
						,Source.[EffectiveTo]
						,Source.[LearnAimRefTitle]
						,Source.[LearnAimRefType]
						,Source.[NotionalNVQLevel]
						,Source.[NotionalNVQLevelv2]
						,Source.[AwardOrgAimRef]
						,Source.[CertificationEndDate]
						,Source.[OperationalStartDate]
						,Source.[OperationalEndDate]
						,Source.[EnglandFEHEStatus]
						,Source.[CreditBasedFwkType]
						,Source.[QltyAssAgencyType]
						,Source.[OfQualGlhMin]
						,Source.[OfQualGlhMax]
						,Source.[DiplomaLinesOfLearning]
						,Source.[FrameworkCommonComponent]
						,Source.[LTRCPWithProviderUpliftFactor]
						,Source.[EntrySubLevel]
						,Source.[SuccessRateMapCode]
						,Source.[AccreditiedNotDfESApproved]
						,Source.[AccreditiedMayPossDfESApproved]
						,Source.[JointInvestmentProgrammeOnly]
						,Source.[OLASSOnly]
						,Source.[UnemployedOnly]
						,Source.[IndependentLivingSkills]
						,Source.[AdditionalOrSpecialistLearning]
						,Source.[EnglPrscID]
						,Source.[Vocational]
						,Source.[AwardOrgCode]
						,Source.[UnitType]
						,Source.[LearningDeliveryGenre]
						,Source.[ApprovedEmployerSchemeFramework]
						,Source.[FrameworkCompletionClassCode]
						,Source.[OfQualOfferedEngland]
						,Source.[OfqualPurpose]
						,Source.[OfqualSubPurpose]
						,Source.[RgltnStartDate]
						,Source.[SourceQualType]
						,Source.[SourceSystemRef]
						,Source.[SourceURLRef]
						,Source.[SourceURLLinkType]
						,Source.[OccupationalIndicator]
						,Source.[AccessHEIndicator]
						,Source.[KeySkillsIndicator]
						,Source.[FunctionalSkillsIndicator]
						,Source.[GCEIndicator]
						,Source.[GCSEIndicator]
						,Source.[ASLevelIndicator]
						,Source.[A2LevelIndicator]
						,Source.[ALevelIndicator]
						,Source.[QCFIndicator]
						,Source.[QCFDiplomaIndicator]
						,Source.[QCFCertificateIndicator]
						,Source.[EFAEnglishGCSE]
						,Source.[EFAMathsGCSE]
						,Source.[EFACOFType]
						,Source.[SFAFundedIndicator]
						,Source.[DanceAndDramaIndicator]
						,Source.[AvailabiltyStatus]
						,Source.[Note]
						,Source.[LearnDirectClassSystemCode1]
						,Source.[LearnDirectClassSystemCode2]
						,Source.[LearnDirectClassSystemCode3]
						,Source.[RegulatedCreditValue]
						,Source.[SectorSubjectAreaTier1]
						,Source.[SectorSubjectAreaTier2]
						,Source.[MI_NotionalNVQLevel]
						,Source.[MI_NotionalNVQLevelv2]
						,Source.[GuidedLearningHours]
						,Source.[DirectStudyHours]
						,Source.[DedicatedAssessmentHours]
						,Source.[TotalQualificationTime]
						,Source.[Created_On]
						,Source.[Created_By]
						,Source.[Modified_On]
						,Source.[Modified_By]
				  )
		WHEN NOT MATCHED BY SOURCE THEN DELETE
		;

		RETURN 0;

	END TRY
-- 
-------------------------------------------------------------------------------------- 
-- Handle any problems
-------------------------------------------------------------------------------------- 
-- 
	BEGIN CATCH

		DECLARE   @ErrorMessage		NVARCHAR(4000)
				, @ErrorSeverity	INT 
				, @ErrorState		INT
				, @ErrorNumber		INT
						
		SELECT	  @ErrorNumber		= ERROR_NUMBER()
				, @ErrorMessage		= 'Error in :' + ISNULL(OBJECT_NAME(@@PROCID),'') + ' - Error was :' + ERROR_MESSAGE()
				, @ErrorSeverity	= ERROR_SEVERITY()
				, @ErrorState		= ERROR_STATE();
	
		RAISERROR (
					  @ErrorMessage		-- Message text.
					, @ErrorSeverity	-- Severity.
					, @ErrorState		-- State.
				  );
			  
		RETURN @ErrorNumber;

	END CATCH
-- 
-------------------------------------------------------------------------------------- 
-- All done
-------------------------------------------------------------------------------------- 
-- 
END